"use client";

import { useEffect, useState } from "react";
import { COMMERCE_FUNCTION, CONSULTATIONS_FUNCTION, money } from "../lib/tlu";

const SESSION_KEY = "tlu_session";
function hasSession(){try{const raw=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");return Boolean(raw?.authenticated||raw?.access_token)}catch{return false}}
function loginUrl(nextPath,productSlug=""){const next=encodeURIComponent(nextPath);return `/login?next=${next}${productSlug?`&product=${encodeURIComponent(productSlug)}`:""}`}
async function post(url,body){const res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));const error=!res.ok?new Error(data?.error||"Request failed"):null;if(error){error.status=res.status;throw error}return data}

export function ConsultationActions({offer,productSlug,resumeProduct="",resumeApplicationId=""}){
  const requiresApplication=Boolean(offer.requires_application);
  const[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[application,setApplication]=useState(null);
  const[form,setForm]=useState({contact_name:"",contact_email:"",contact_phone:"",company_name:"",website_url:"",primary_goal:"",current_challenge:"",desired_outcome:"",budget_range:"",timeline:"",website_field:""});

  async function loadApplication(){if(!hasSession()||!requiresApplication)return;try{const data=await post(CONSULTATIONS_FUNCTION,{action:"my_application",offer_slug:offer.slug});setApplication(data.application||null)}catch(e){if(e.status!==401)setError(e.message)}}
  useEffect(()=>{loadApplication()},[offer.slug]);
  useEffect(()=>{if(resumeProduct===productSlug&&hasSession()){const guard=`tlu_consult_resume:${productSlug}:${resumeApplicationId||"direct"}`;if(sessionStorage.getItem(guard))return;sessionStorage.setItem(guard,"1");startCheckout(resumeApplicationId||application?.id||"").catch(()=>sessionStorage.removeItem(guard))}},[resumeProduct,productSlug,resumeApplicationId,application?.id]);

  async function startCheckout(applicationId=""){
    const nextPath=`/consultations/${offer.slug}${applicationId?`?application=${encodeURIComponent(applicationId)}`:""}`;
    if(!hasSession()){window.location.href=loginUrl(nextPath,productSlug);return}
    setBusy(true);setError("");setMessage("");
    try{const data=await post(COMMERCE_FUNCTION,{action:"create_checkout",product_slug:productSlug,application_id:applicationId||undefined,origin:window.location.origin});if(!data.checkout_url)throw new Error("Secure checkout URL was not returned");window.location.href=data.checkout_url}catch(e){setError(e.message);setBusy(false);throw e}
  }

  async function submitApplication(e){e.preventDefault();setBusy(true);setError("");setMessage("");try{const data=await post(CONSULTATIONS_FUNCTION,{action:"submit_application",offer_slug:offer.slug,...form,source:"university_web"});setApplication(data.application||{status:"submitted",id:data.application?.id});setMessage("Application received. The Strategy Room will review fit, scope and timing before deposit access opens.");setForm(v=>({...v,primary_goal:"",current_challenge:"",desired_outcome:""}))}catch(e){setError(e.message)}finally{setBusy(false)}}

  if(!requiresApplication)return <div className="consult-action-panel"><div><small>DIRECT ACCESS</small><h3>{offer.name}</h3><p>Secure the session now. Scheduling is handled immediately after payment confirmation.</p></div><button className="primary-action" disabled={busy} onClick={()=>startCheckout()}>{busy?"Opening secure checkout…":`Secure access · ${offer.price_label||money(offer.price_cents)}`}</button>{error?<p className="form-error">{error}</p>:null}</div>;

  const qualified=application&&["qualified","payment_sent"].includes(application.status);
  const paid=application&&["paid","booked","completed"].includes(application.status);
  if(qualified)return <div className="consult-action-panel qualified"><div><small>APPLICATION APPROVED</small><h3>Your deposit access is open.</h3><p>Complete the deposit to lock your Strategy Room engagement.</p></div><button className="primary-action" disabled={busy} onClick={()=>startCheckout(application.id)}>{busy?"Opening secure checkout…":`Pay deposit · ${money(offer.deposit_cents)}`}</button>{error?<p className="form-error">{error}</p>:null}</div>;
  if(paid)return <div className="consult-action-panel qualified"><div><small>PAYMENT CONFIRMED</small><h3>Your engagement is active.</h3><p>{application.next_action||"Scheduling handoff is next."}</p></div></div>;
  if(application)return <div className="consult-action-panel pending"><div><small>APPLICATION {String(application.status||"submitted").replaceAll("_"," ").toUpperCase()}</small><h3>Your Strategy Room request is in the queue.</h3><p>{application.next_action||"Qualification review is next."}</p></div><button className="ghost-action" onClick={loadApplication}>Refresh status</button>{error?<p className="form-error">{error}</p>:null}</div>;

  return <form className="consult-form" onSubmit={submitApplication}><div className="consult-form-head"><small>APPLICATION REQUIRED</small><h3>Show us the decision, not a polished pitch.</h3><p>We use this to determine fit, scope and which advisory format creates the most leverage.</p></div><div className="consult-form-grid"><label>Your name<input required value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></label><label>Email<input required type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label><label>Phone<input value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/></label><label>Company / brand<input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/></label><label>Website<input value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})}/></label><label>Budget range<input value={form.budget_range} onChange={e=>setForm({...form,budget_range:e.target.value})} placeholder="Example: $5K–$10K"/></label><label>Timeline<input value={form.timeline} onChange={e=>setForm({...form,timeline:e.target.value})} placeholder="Example: next 30 days"/></label><input tabIndex="-1" autoComplete="off" className="consult-honeypot" value={form.website_field} onChange={e=>setForm({...form,website_field:e.target.value})}/></div><label>Primary goal<textarea required minLength={20} rows={4} value={form.primary_goal} onChange={e=>setForm({...form,primary_goal:e.target.value})}/></label><label>Current challenge<textarea required minLength={20} rows={4} value={form.current_challenge} onChange={e=>setForm({...form,current_challenge:e.target.value})}/></label><label>Desired outcome<textarea required minLength={20} rows={4} value={form.desired_outcome} onChange={e=>setForm({...form,desired_outcome:e.target.value})}/></label><button className="primary-action" disabled={busy}>{busy?"Submitting…":"Submit Strategy Room application"}</button>{message?<p className="form-message">{message}</p>:null}{error?<p className="form-error">{error}</p>:null}<p className="consult-signin-note">Already applied? <a href={`/login?next=${encodeURIComponent(`/consultations/${offer.slug}`)}`}>Sign in with the same email to check status.</a></p></form>;
}

export function ConsultationCheckoutSuccess({sessionId}){
  const[state,setState]=useState({status:"working",message:"Verifying payment and activating your Strategy Room engagement…",data:null});
  useEffect(()=>{if(!hasSession()){setState({status:"error",message:"Sign in with the same operator profile used for checkout to finish activation.",data:null});return}post(COMMERCE_FUNCTION,{action:"confirm_checkout",session_id:sessionId}).then(data=>setState({status:"done",message:"Payment confirmed. Your Strategy Room engagement is active.",data})).catch(e=>setState({status:"error",message:e.message,data:null}))},[sessionId]);
  return <div className={`status-card status-card-v2 ${state.status}`}><span>{state.status==="done"?"✓":state.status==="error"?"!":"↻"}</span><small>STRATEGY ROOM STATUS</small><h2>{state.message}</h2>{state.status==="done"?<>{state.data?.booking_url?<a className="primary-action link-button" href={state.data.booking_url}>Schedule your session</a>:<p>Scheduling handoff is queued. Your paid consultation record is saved in the system.</p>}<a href="/dashboard">Open Operator Console →</a></>:state.status==="error"?<a href="/login?next=/consultations/checkout/success">Return to operator access</a>:null}</div>;
}

export function ConsultationAdminQueue(){const[data,setData]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState("");async function load(){setError("");try{const r=await post(CONSULTATIONS_FUNCTION,{action:"admin_queue"});setData(r.queue||[])}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);async function review(id,decision){setBusy(id+decision);try{await post(CONSULTATIONS_FUNCTION,{action:"review_application",application_id:id,decision,qualification_score:decision==="qualified"?85:0,reviewer_notes:decision==="qualified"?"Qualified for Strategy Room payment access.":"Reviewed by Strategy Room."});await load()}catch(e){setError(e.message)}finally{setBusy("")}}return <div className="consult-admin">{error?<div className="status-card error"><h2>{error}</h2></div>:null}<div className="console-section-head"><div><div className="section-label">STRATEGY ROOM PIPELINE</div><p>Applications waiting for qualification, payment or scheduling.</p></div><button className="ghost-action" onClick={load}>Refresh</button></div><div className="consult-admin-list">{data.map(item=><article key={item.id}><div><small>{item.tlu_consultation_offers?.name} · {new Date(item.created_at).toLocaleDateString()}</small><h3>{item.contact_name}</h3><p>{item.contact_email}{item.company_name?` · ${item.company_name}`:""}</p></div><div><small>GOAL</small><p>{item.primary_goal}</p><small>CHALLENGE</small><p>{item.current_challenge}</p></div><div className="consult-admin-status"><b>{item.status.replaceAll("_"," ")}</b><span>{item.payment_status}</span>{["submitted","under_review"].includes(item.status)?<><button disabled={busy} onClick={()=>review(item.id,"qualified")}>Qualify</button><button disabled={busy} onClick={()=>review(item.id,"declined")}>Decline</button></>:null}</div></article>)}</div></div>}
