"use client";

import { useEffect, useState } from "react";
import { LMS_FUNCTION } from "../lib/tlu";

const SESSION_KEY="tlu_session";
function readSession(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");if(!s)return null;if(s.refresh_token||(s.access_token&&s.access_token!=="cookie-session")){localStorage.removeItem(SESSION_KEY);return null}return s.authenticated||s.access_token?{authenticated:true,access_token:"cookie-session",user:s.user||null}:null}catch{return null}}
async function invoke(token,body){const res=await fetch(LMS_FUNCTION,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok){if(res.status===401){localStorage.removeItem(SESSION_KEY);window.location.href="/login?next=/admin/review"}throw new Error(data?.error||"Review request failed")}return data}

export default function ReviewQueue(){const[queue,setQueue]=useState(null),[error,setError]=useState("");async function load(){const s=readSession();if(!s?.access_token){window.location.href="/login?next=/admin/review";return}try{const d=await invoke(s.access_token,{action:"admin_review_queue"});setQueue(d.queue||[])}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);if(error)return <div className="status-card error"><small>REVIEW ACCESS</small><h2>{error}</h2></div>;if(!queue)return <div className="status-card loading-card"><small>PROOF REVIEW</small><h2>Loading reviewer queue…</h2></div>;return <div className="review-stack"><section className="review-overview"><article><small>OPEN PROOF BUILDS</small><b>{queue.filter(i=>i.status==="submitted").length}</b></article><article><small>REVISION QUEUE</small><b>{queue.filter(i=>i.status==="needs_revision").length}</b></article><article><small>REVIEW STANDARD</small><b>80%</b></article></section>{queue.length?queue.map(item=><ReviewCard key={item.id} item={item} onDone={load}/>):<div className="review-empty"><small>QUEUE CLEAR</small><h2>No Proof Builds are waiting for review.</h2><p>New submissions will appear here automatically.</p></div>}</div>}

function ReviewCard({item,onDone}){const[score,setScore]=useState(item.score??80),[feedback,setFeedback]=useState(item.feedback||""),[busy,setBusy]=useState(false),[error,setError]=useState("");const a=item.tlu_assessments||{};async function grade(decision){const s=readSession();if(!s?.access_token)return;setBusy(true);setError("");try{await invoke(s.access_token,{action:"grade_assessment",attempt_id:item.id,decision,score:Number(score),feedback});await onDone()}catch(e){setError(e.message)}finally{setBusy(false)}}return <article className="review-card"><div className="review-card-head"><div><small>{a.tlu_courses?.title||"FLAGSHIP"} · ATTEMPT {String(item.attempt_no).padStart(2,"0")}</small><h2>{a.title||"Proof Build"}</h2><p>{item.tlu_profiles?.full_name||"Operator"} · {item.tlu_profiles?.email||""}</p></div><div className={`review-status ${item.status}`}><span>{item.status.replaceAll("_"," ").toUpperCase()}</span><small>{item.submitted_at?new Date(item.submitted_at).toLocaleString():""}</small></div></div><div className="review-body"><div className="review-responses">{Object.entries(item.responses||{}).map(([key,value],i)=><section key={key}><small>{String(i+1).padStart(2,"0")} · {key.replaceAll("_"," ").toUpperCase()}</small><p>{String(value)}</p></section>)}</div><aside className="review-score"><small>PROOF RUBRIC</small>{(a.rubric?.dimensions||[]).map(d=><div key={d.name}><span>{d.name}</span><b>{d.points} pts</b></div>)}<label>Final score<input type="number" min="0" max="100" value={score} onChange={e=>setScore(e.target.value)}/></label><label>Reviewer feedback<textarea rows="8" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="State what passed, what needs revision, and the next action."/></label></aside></div>{item.evidence?.length?<div className="review-evidence"><small>EVIDENCE RECEIPTS</small><div>{item.evidence.map((e,i)=><a href={e.url} target="_blank" rel="noreferrer" key={e.path}>{String(i+1).padStart(2,"0")} · {e.name} ↗</a>)}</div></div>:null}{error?<p className="form-error">{error}</p>:null}<div className="review-actions"><button className="ghost-action" disabled={busy} onClick={()=>grade("needs_revision")}>Return for Revision</button><button className="primary-action" disabled={busy} onClick={()=>grade("passed")}>{busy?"Saving Decision…":"Approve Proof Build"}</button></div></article>}
