import Link from "next/link";
import { getCatalog, money } from "./lib/tlu";
import { LINGO, programMeta } from "./lib/lingo";

export const dynamic = "force-dynamic";

export default async function Home() {
  const { courses, faqs, services, consultations, templates, glossary } = await getCatalog();
  return <main className="site-shell">
    <div className="utility-strip"><span>THE LIFESTYLE UNIVERSITY</span><span>OPERATOR EDUCATION · SYSTEMS · EXECUTION</span><span>BUILD WHAT PAYS</span></div>
    <nav className="nav nav-premium"><Link className="brand" href="/"><b>THE LIFESTYLE</b><span>UNIVERSITY</span></Link><div><a href="#programs">Flagships</a><a href="#resources">Tool Vault</a><a href="#consultations">Strategy Room</a><a href="#services">Build Desk</a><Link className="console-link" href="/dashboard">Operator Console</Link></div></nav>

    <section className="hero hero-v2">
      <div className="hero-gridline" />
      <div className="eyebrow-row"><span>THE OPERATOR ACADEMY</span><span>10 FLAGSHIP PROGRAMS</span></div>
      <h1>KNOWLEDGE ISN’T<br/><em>THE PRODUCT.</em><br/>EXECUTION IS.</h1>
      <div className="hero-bottom"><p>For founders, curators, creators and operators building real revenue systems across culture, hospitality, media, products, services and technology.</p><div className="hero-actions"><a className="primary-action link-button" href="#programs">Enter the Flagships</a><Link className="ghost-action" href="/dashboard">Open Operator Console →</Link></div></div>
      <div className="hero-stats hero-stats-v2"><div><b>{courses.length || 10}</b><span>Flagship Programs</span></div><div><b>320</b><span>Operator Plays</span></div><div><b>105+</b><span>Tools in the Vault</span></div><div><b>90</b><span>Gates + Proof Builds</span></div></div>
    </section>

    <section className="journey-band"><div><small>THE BUILD METHOD</small><div className="journey-flow"><span>01 · STAGE</span><i>→</i><span>02 · PLAY</span><i>→</i><span>03 · BUILD</span><i>→</i><span>04 · STAGE GATE</span><i>→</i><span>05 · PROOF BUILD</span><i>→</i><span>06 · CREDENTIAL</span></div></div></section>

    <section className="three-paths three-paths-v2"><article><div className="path-number">01</div><small>LEARN IT</small><h2>Flagship Programs</h2><p>Install complete operating systems through Stages, Plays, Builds, Stage Gates and a final Proof Build.</p><a href="#programs">Enter the curriculum →</a></article><article><div className="path-number">02</div><small>DECIDE IT</small><h2>Strategy Room</h2><p>Bring the decision, bottleneck or opportunity that needs senior-level pressure testing—not another generic call.</p><a href="#consultations">Book advisory →</a></article><article><div className="path-number">03</div><small>BUILD IT</small><h2>Build Desk</h2><p>Move approved strategy into execution: sites, systems, brands, funnels, apps, decks, creative and operating infrastructure.</p><a href="#services">Hand us the build →</a></article></section>

    <section id="programs" className="section programs-section"><header className="section-head section-head-v2"><div><small>THE 10 FLAGSHIPS</small><p>Choose the business system closest to your current bottleneck.</p></div><h2>MASTER THE SYSTEM.<br/><em>OWN THE OUTCOME.</em></h2></header><div className="course-grid course-grid-v2">{courses.map((c, i) => <article className="course-card course-card-v2" key={c.id}><div className="course-topline"><span>SCHOOL {String(i+1).padStart(2,"0")}</span><span>{c.school_name || "OPERATOR STUDIES"}</span></div><div className="course-index">{String(i+1).padStart(2,"0")}</div><h3>{c.title}</h3><p className="course-promise">{c.transformation_promise || c.description}</p><div className="course-meta">{programMeta(c.lesson_count || 32).map(item => <span key={item}>{item}</span>)}</div><div className="course-foot"><div><small>PROGRAM INVESTMENT</small><b>{c.price_label || money(c.price_cents)}</b></div><Link href={`/courses/${c.slug}`}>Enter program <span>↗</span></Link></div></article>)}</div></section>

    <section id="resources" className="section resources resources-v2"><header className="section-head section-head-v2"><div><small>{LINGO.resources.toUpperCase()}</small><p>Working assets built to be used, delegated and measured.</p></div><h2>LESS THEORY.<br/><em>MORE LEVERAGE.</em></h2></header><div className="resource-metrics resource-metrics-v2"><div><b>{templates.length || 105}+</b><span>Operator Tools</span></div><div><b>{glossary.length || 30}+</b><span>Business Terms</span></div><div><b>8</b><span>Core Playbooks</span></div><div><b>{faqs.length || 15}+</b><span>Decision Answers</span></div></div><div className="resource-list resource-list-v2">{templates.slice(0,12).map((t,i) => <article key={t.slug}><div className="resource-code">TV-{String(i+1).padStart(3,"0")}</div><small>{t.category}</small><h3>{t.title}</h3><p>{t.preview_text || t.description}</p><span>{t.access_level === "free" ? "OPEN ACCESS" : "PROGRAM ACCESS"}</span></article>)}</div></section>

    <section id="consultations" className="section split-section strategy-room"><header className="section-head section-head-v2"><div><small>THE STRATEGY ROOM</small><p>Use advisory when the cost of a bad decision is higher than the price of expert clarity.</p></div><h2>PRESSURE-TEST<br/><em>THE DECISION.</em></h2></header><div className="offer-list offer-list-v2">{consultations.slice(0,8).map((o,i) => <article key={o.slug}><div className="offer-sequence">{String(i+1).padStart(2,"0")}</div><div className="offer-copy"><small>{o.offer_kind || "ADVISORY"}</small><h3>{o.name}</h3><p>{o.description || `${o.duration_minutes || 60}-minute focused advisory session.`}</p></div><div className="offer-price"><small>ACCESS</small><b>{o.price_label || money(o.price_cents)}</b></div></article>)}</div></section>

    <section id="services" className="section services services-v2"><header className="section-head section-head-v2"><div><small>THE BUILD DESK</small><p>Execution services for operators who want the finished asset—not another recommendation.</p></div><h2>STRATEGY APPROVED.<br/><em>NOW SHIP IT.</em></h2></header><div className="service-grid service-grid-v2">{services.map((s,i) => <article key={s.slug}><div className="service-number">{String(i+1).padStart(2,"0")}</div><small>{s.category}</small><h3>{s.title}</h3><p>{s.description || "Done-for-you implementation built from the operating strategy."}</p><div><b>{s.price_label || (s.starting_price_cents ? `From ${money(s.starting_price_cents)}` : "Request scope")}</b><span>{s.turnaround_label || "Scoped delivery"}</span></div></article>)}</div></section>

    <section className="section faq faq-v2"><header className="section-head section-head-v2"><div><small>BEFORE YOU ENTER</small><p>The questions serious operators ask before committing.</p></div><h2>KNOW THE STANDARD.<br/><em>THEN ENTER.</em></h2></header><div>{faqs.slice(0,12).map((f,i) => <details key={f.id || f.question}><summary><span>{String(i+1).padStart(2,"0")}</span>{f.question}</summary><p>{f.answer}</p></details>)}</div></section>

    <section className="closing closing-v2"><small>THE LIFESTYLE UNIVERSITY</small><h2>DON’T COLLECT COURSES.<br/><em>COLLECT CAPABILITY.</em></h2><p>Choose the flagship closest to the money, system or decision you need to improve. Enter with a problem. Leave with an operating asset.</p><a className="primary-action link-button" href="#programs">Choose your flagship</a></section>
    <footer className="footer-v2"><div className="brand"><b>THE LIFESTYLE</b><span>UNIVERSITY</span></div><p>Operator education for culture, commerce and experience.</p><Link href="/dashboard">Operator Console →</Link></footer>
  </main>;
}
